### ISSUE TITLE
Dear. PresntKim

### ISSUE THREAD

**Issue by raidksh** [PresentKim/GeometryAPI-PMMP#3]
안녕하세요, 프레젠트김님의 플러그인을 애용하고 있는 마인크래프트 서버 운영자 중 한 명입니다.

항상 고마운 마음으로 플러그인 잘 사용하고 있습니다.
플러그인을 판매하는 분들과는 다르게 어떠한 이득도 없이 넓은 아량으로 무료로 사용할 수 있게 해주셔서 너무 감사드립니다.

한데, 깃허브를 이용하는 한 유저로서 불편하고 추가되었으면 하는 부분이 있습니다.

1. README에 한글로 자세하고 정확하게 플러그인 설명을 추가해주셨으면 좋겠어요.
2. 따로 깃허브에 자세한 설명 추가 작업이 귀찮다면 해당 플러그인의 설명이 있는 밴드, 카페 등등 주소를 README에 기재해주시면 좋겠어요.

저도 운영자인지라 설명을 추가한다는 게 귀찮은 작업임을 알고 있습니다.
하지만, 플러그인 이해가 부족하다는 이유로 사용하지 못한다는 점에 안타까울 뿐입니다.

이 글을 읽어주실지도 모르겠네요.

항상 감사하게 생각하고 사용 중입니다. 감사합니다.

**Comment by PresentKim** [comment]
주 타겟층이 한국인이 아닌 이상 한글 설명을 별도로 첨부할 이유가 없습니다.
~~사실 영어 설명 부터도 귀찮아서 부실한 경우가 대부분입니다~~
또한 번역기를 통해 충분히 번역이 가능하다고 판단됩니다.
